version: '1.{build}'
image: Visual Studio 2022

# Set .NET SDK version
environment:
  DOTNET_VERSION: 8.x

# Build Configuration
configuration: Release
platform: Any CPU

# Install dependencies
install:
  - cmd: dotnet restore

before_build:
  - choco install codecov
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m

build_script:
  - cmd: dotnet build

test_script:
  - cmd: dotnet tool install Codecov.Tool --version 1.10.0 --tool-path tools
  - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - codecov -f ".\ReadTimeEstimator.Tests\coverage.opencover.xml"
